version: '2'
services:
  magento2-data:
    image: mysql:5.7
    entrypoint: /bin/true

  magento2-mysql:
    image: mysql:5.7
    container_name: magento2-mysql
    volumes_from:
        - magento2-data
    environment:
      - MYSQL_USER=magento2
      - MYSQL_PASSWORD=magento2
      - MYSQL_DATABASE=magento2
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  magento2-server:
    build: .
    container_name: magento2-server
    depends_on:
      - magento2-mysql
    ports:
      - '8090:80'
    links:
      - magento2-mysql:mysql
    volumes_from:
      - magento2-data
    environment:
      - MAGENTO_ADMIN_FIRSTNAME=Admin
      - MAGENTO_ADMIN_LASTNAME=User
      - MAGENTO_ADMIN_EMAIL=admin@example.com
      - MAGENTO_ADMIN_USER=admin
      - MAGENTO_ADMIN_PASSWORD=magento2
      - MAGENTO_DB_HOST=mysql
      - MAGENTO_DB_NAME=magento2
      - MAGENTO_DB_USER=magento2
      - MAGENTO_DB_PASSWORD=magento2
      - MAGENTO_BACKEND_FRONTNAME=admin